### PR TITLE
plot fitted  vs observed in plot.model_performance_explainer

### PR DESCRIPTION
**Pull request by mstaniak**
can we have this for the workshop?

### CODE REVIEW

**Comment by pbiecek** [comment]
Sure, but please add a test that covers added code (to the tests directory), 
otherwise codecov fails

**Comment by mstaniak** [comment]
Will do

**Comment by pbiecek** [comment]
@agosiewska is the `observed` vs `predicted` plot handled by `auditor`? 
It looks more like a model diagnostic plot than a model performance plot. 

Let's talk about the integration of auditor and DALEX on Tuesday. 
One challenge is the naming convention, CamelCase from auditor vs _ notation from DALEX. 
Maybe it's not a problem if all `plotXXX` functions can be accessed through the generic `plot()`.

Possible smooth interfaces

* add a generic `auditor::audit.explainer()` that will handle DALEX explainers by the auditor
* add a new explainer `DALEX::model_diagnostic()` that will be a wrapper around the auditor.

**Comment by agosiewska** [comment]
There was no such plot in `auditor`. I added it with the name `plotPrediction()`.

I am planning to modify names of some functions, but I would prefer to stay with CamelCase. However, I will make sure that all plots are available via `plot()`.

I'm ok with both your suggestions about the interface and I am very happy to talk about this on Tuesday.

**Comment by mstaniak** [comment]
adding this to DALEX before 14.05 would be great, I could advertise auditor during my part of the erum workshop (:

**Comment by pbiecek** [comment]
@agosiewska let's have both links between these packages. 
It would be great to add `auditor::audit.explainer()` and sent `auditor` to CRAN before eRum (is it  possible?).
I will work on `DALEX::model_diagnostic()` and add a new section to https://pbiecek.github.io/DALEX_docs/ (Model Diagnostics - auditor related stuff). But this may take more time.

**Comment by agosiewska** [comment]
@pbiecek Ok, I'll work on `auditor::audit.explainer()` and start preparing the package to be submitted to CRAN.

**Comment by pbiecek** [comment]
Thanks!

**Comment by pbiecek** [comment]
@agosiewska Thanks, new `audit.explainer` is working great
```
library("DALEX")
library("randomForest")
library(auditor)
set.seed(59)

apartments_rf_model <- randomForest(m2.price ~ construction.year + surface + floor + 
                                      no.rooms + district, data = apartments)
explainer_rf <- explain(apartments_rf_model, 
                        data = apartmentsTest, y = apartmentsTest$m2.price)

au_rf <- audit(explainer_rf)
plotResiduals(au_rf)
plotResiduals(au_rf, variable = "m2.price")
plotPrediction(au_rf)
```

@mstaniak Let's keep functions for model diagnostic in `auditor` while `DALEX` will be just a glue/common interface to other packages like `pdp`/`live`/`breakDown`/`factorMerger`/`auditor` etc.

**Comment by mstaniak** [comment]
ok, great

**Pull request closed without merging**
