### PR TITLE
Adding plot functionality to model_performance #34

### PR DESCRIPTION
**Pull request by 12tafran**
This is my version of the enhancement

This change:

- add in an `index` column in `model_performance` and replaced `name` parameter with `index` in `plot_model_performance`

https://github.com/pbiecek/DALEX/issues/34

### CODE REVIEW

**Comment by pbiecek** [comment]
Thanks. 
This PR changes behaviour of current function thus it may break code of sombodys else.
It would be better to add a parameter (e.g. `label`) to the `plot.model_performance_explainer` function, the default value may be `name` (this will not change behaviour for existing code) but with `index` it will plot indexes instead of names. 
What do you think about this?

**Comment by 12tafran** [comment]
That make sense.  I can adjust the code so that there won't be any changes to the output of `model_performance` and add the option for user to adjust what they want the name of the outlier point to be in `plot.model_performance_explainer`.  There's might be an issue if users were to rearrange the `model_performance` output before running the `plot.model_performance_explainer` since the order of the output will ultimately dictates what the `index` will be.  I really don't foresee this to be an issue but it's just something to keep in mind.

**Comment by 12tafran** [comment]
On a separate note, following your example on https://pbiecek.github.io/DALEX/reference/plot.model_performance_explainer.html , if you rearrange the order of arguments from plot(mp_rf, mp_glm, mp_lm, geom = "boxplot", show_outliers = 1) to plot(mp_glm, mp_lm, mp_rf, geom = "boxplot", show_outliers = 1), you will get a graph where the outliers don't match the model.

It seems like we have to input the models best to worst in terms of root mean square of residuals for it to work properly

Not sure if this is an issue for you as well.

I can open another issue to keep everything clear if you like, I just figure since we are digging into the code here, we can address here as well

**Comment by pbiecek** [comment]
Thank you for the PR. 

And yes, please open an issue related to the order of models (just copy paste from the comment above).
I do not know how easy it is to fix it, but if possible then it would be best to get same results for every ordering.

**Pull request merged**
