### PR TITLE
adds message for as.factor(y) = T

### PR DESCRIPTION
**Pull request by mstaniak**
Although it is written in the documentation, this part can be confusing for some users (tested on students). After this change, explain() will print a message when the user passes a factor/character vector as y in case of binary classification.

### CODE REVIEW

**Comment by pbiecek** [comment]
@mstaniak I do not understand this part `length(y) == 2`

**Comment by mstaniak** [comment]
corrected it in the last commit

**Comment by pbiecek** [comment]
@mstaniak 
What about following message: Factor provided as y. The default loss functions assume numerical outputs (e.g. scores, probabilities, rates). Consider changing the y to the logical or numerical (0-1) vector.

**Comment by mstaniak** [comment]
Definitely more informative. Updated.

**Comment by pbiecek** [comment]
Thanks, but now you have 'Factor provided as y. Factor provided as y. ' twice ;-)

Btw, maybe it should in the the more active "Please note, that 'y' is a factor."

**Pull request merged**
